# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Swift 台灣
tagline:          'Swift 程式語言 台灣社群站'
description:      'Swift 程式語言 台灣社群站'
url:              https://swiftlang.tw
enforce_ssl:      swiftlang.tw
baseurl:          /

author:
  name:           'John Lin'
  url:            https://twitter.com/johnlinvc

paginate:         5
paginate_path: "/blog/page:num/"

# Custom vars
version:          15.12.23.0

github:
        repo:           'https://github.com/swift-tw/swift-tw.github.io'
