# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Swift 台灣
tagline:          'Swift 程式語言 台灣社群站'
description:      'Swift 程式語言 台灣社群站'
url:              https://swiftlang.tw
enforce_ssl:      swiftlang.tw
baseurl:          /

author:
  name:           'John Lin'
  url:            https://twitter.com/johnlinvc

#remove paginate for jekyll 3
#paginate:         5
#paginate_path:    "/blog/page:num/"
excerpt_separator: <!--more-->

# Custom vars
version:          16.2.19.0

github:
        repo:           'https://github.com/swift-tw/swift-tw.github.io'
